### ISSUE TITLE
[BUG] GCP Compute Api Restricted

### ISSUE THREAD

**Issue by awils27** [state-of-the-art/BlendNet#158] opened 2021-12-17 15:27 UTC
I am receiving an error stating the compute API is restricted however I am unable to find any resources around this, I've made sure I have compute admin in the IAM panel for the account logged into Gcloud but i'm not sure what else to try.

### Environment:
Blender 2.93LTS and Blendnet 0.3.9
Windows 10

![image](https://user-images.githubusercontent.com/68633820/146567327-220e33bf-7992-4441-9290-4099fe58ed73.png)

Cannot seem to copy from Blenders addons panel so heres a screenshot

Perhaps a list of common problems and solutions in the wiki could be of some help (if there is a simple fix for this that I am missing)

**Comment by rabits** [comment] 2021-12-17 18:17
Hi @awils27 , could you please specify the google cloud sdk version you using? I will check with the latest and will try to reproduce.

**Comment by awils27** [comment] 2021-12-18 01:12
Hello

here is the information from running `gcloud version`

Google Cloud SDK 367.0.0
bq 2.0.72
core 2021.12.10
gsutil 5.5

**Comment by awils27** [comment] 2021-12-18 01:26
As per issue #150 I decided to try to revert google cloud to 329.0.0 as suggested in that issue to test if it was still doing with an older gcloud sdk using this command.

`gcloud components update --version 329.0.0`

This gave me the same overall error, compute engine API restricted, but with different reason OAuthCredientials 
![image](https://user-images.githubusercontent.com/68633820/146624275-81382db3-d2f9-453b-90e6-a79013da8405.png)

**Comment by rabits** [comment] 2021-12-21 19:21
Ok, found the error in Addon:
```
WARN: Catched exception from "gcp" provider execution of getResources: module 'googleapiclient.discovery_cache' has no attribute 'get_static_doc'
ERROR: Unable to get the GCP machine type info for: n1-standard-1
Traceback (most recent call last):
  File "/home/user/.config/blender/3.0/scripts/addons/blendnet/BlendNet/providers/__init__.py", line 72, in _execProviderFunc
    return getattr(modules[selected_provider], func)(*args, **kwargs)
  File "/home/user/.config/blender/3.0/scripts/addons/blendnet/BlendNet/providers/gcp/__init__.py", line 717, in getResources
    compute, configs = _getCompute(), _getConfigs()
  File "/home/user/.config/blender/3.0/scripts/addons/blendnet/BlendNet/providers/gcp/__init__.py", line 155, in _getCompute
    return googleapiclient.discovery.build('compute', 'v1', credentials=creds)
  File "/srv/user/local/google-cloud-sdk/platform/bq/third_party/googleapiclient/_helpers.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/srv/user/local/google-cloud-sdk/platform/bq/third_party/googleapiclient/discovery.py", line 291, in build
    content = _retrieve_discovery_doc(
  File "/srv/user/local/google-cloud-sdk/platform/bq/third_party/googleapiclient/discovery.py", line 401, in _retrieve_discovery_doc
    content = discovery_cache.get_static_doc(serviceName, version)
AttributeError: module 'googleapiclient.discovery_cache' has no attribute 'get_static_doc'
```
Seems they added static_discovery which is not working by default. Specified it as `False` and seems working now. Will merge the PR asap, but seems the new version need to wait for Blender v3 support (#156).

**Comment by rabits** [comment] 2021-12-21 19:27
@awils27 could you please check the fixed build if it's working for you?:
* zip: https://2367-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.10-62a4d88.zip
* tar.gz: https://2367-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.10-62a4d88.tar.gz

**Comment by awils27** [comment] 2021-12-22 00:52
It is connecting properly now without error and I can make a manager instance and it shows up in the cloud console however I get an error trying to connect to the manager.

> Dec 22 00:43:14 blendnet-s22edw-manager systemd[2358]: blendnet-manager.service: Failed to execute command: Permission denied
> Dec 22 00:43:14 blendnet-s22edw-manager systemd[2358]: blendnet-manager.service: Failed at step EXEC spawning /srv/blender/blender: Permission denied
> Dec 22 00:43:14 blendnet-s22edw-manager systemd[1]: blendnet-manager.service: Main process exited, code=exited, status=203/EXEC
> Dec 22 00:43:14 blendnet-s22edw-manager systemd[1]: blendnet-manager.service: Failed with result 'exit-code'.
> 

Not sure if this is related or not and i'm happy to create another github issue.


Heres the full log 
[blendnet-s22edw-manager_211222-104500.log](https://github.com/state-of-the-art/BlendNet/files/7759134/blendnet-s22edw-manager_211222-104500.log)

**Comment by rabits** [comment] 2022-01-03 19:56
Hi @awils27 , could you please tell me what the settings are you using to run the manager? The most important one - is blendnet addon preferences blender url - maybe you using the custom one? I just started the manager on GCP and it looks like working fine with blender v3 and linux as addon host.

**Comment by awils27** [comment] 2022-01-04 02:39
I'm not sure where I can find blendnet addon preferences blender url so I probably haven't changed it.

I tried a fresh clone of master and blender 3.0 and it still isn't connecting although I think for a different reason. heres the log.

[blendnet-7jwmkf-manager_220104-123057.log](https://github.com/state-of-the-art/BlendNet/files/7805062/blendnet-7jwmkf-manager_220104-123057.log)

**Comment by rabits** [comment] 2022-01-04 03:16
Yeah this one is not connecting due to the issue fixed in this change - it was only merged to blendnet v0.3.

The addon preferences you can find in here (Edit->Preferences->Add-ons->Blendnet): https://raw.githubusercontent.com/wiki/state-of-the-art/BlendNet/doc/blender_prefs_addon_gcp_provider.png - I would only need to know if you're using a custom Blender dist, or something is odd in the configuration you have for the GCP provider.

Let's stick to the v0.3 for now - and I will also cherry-pick the fix into the master shortly.

**Comment by awils27** [comment] 2022-01-04 04:42
ok switched back to the version linked here

> @awils27 could you please check the fixed build if it's working for you?:
> 
> * zip: https://2367-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.10-62a4d88.zip
> * tar.gz: https://2367-215957316-gh.circle-artifacts.com/0/results/dist/blendnet-0.3.10-62a4d88.tar.gz

Heres a screenshot of the blendnet settings
![Capture](https://user-images.githubusercontent.com/68633820/148010387-8965ead7-97e6-4b0e-aa9c-418e78ee1f1b.PNG)

Get this error:

> Jan  4 04:40:04 blendnet-v1azbl-manager systemd[2114]: blendnet-manager.service: Failed to execute command: No such file or directory
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[2114]: blendnet-manager.service: Failed at step EXEC spawning /srv/blender/blender: No such file or directory
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Main process exited, code=exited, status=203/EXEC
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Failed with result 'exit-code'.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Service RestartSec=100ms expired, scheduling restart.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Scheduled restart job, restart counter is at 5.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: Stopped BlendNet Manager Service.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Start request repeated too quickly.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: blendnet-manager.service: Failed with result 'exit-code'.
Jan  4 04:40:04 blendnet-v1azbl-manager systemd[1]: Failed to start BlendNet Manager Service.

**Comment by rabits** [comment] 2022-01-04 05:11
Yeah, it looks weird - you see, for some reason `Agents type` is grayed out... Could you please attach the Addon log (you can run blender from terminal to get it or in windows there is console available in the menu somewhere).

In the manager logs you attached I see that the blender is unpacking well:
```
Dec 22 00:42:07 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: --> Download & unpack blender
Dec 22 00:42:43 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: -: OK
Dec 22 00:42:45 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 102379520 (98MiB, 44MiB/s)
Dec 22 00:42:47 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 204779520 (196MiB, 46MiB/s)
Dec 22 00:42:50 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 307179520 (293MiB, 45MiB/s)
Dec 22 00:42:52 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 409579520 (391MiB, 45MiB/s)
Dec 22 00:42:55 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 511979520 (489MiB, 42MiB/s)
Dec 22 00:42:58 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script: tar: Unpacked r: 614379520 (586MiB, 41MiB/s)
```

And the error you see for some reason are different now:
```
Dec 22 00:43:13 blendnet-s22edw-manager systemd[1]: Started BlendNet Manager Service.
Dec 22 00:43:13 blendnet-s22edw-manager google_metadata_script_runner[520]: startup-script exit status 0
Dec 22 00:43:13 blendnet-s22edw-manager google_metadata_script_runner[520]: Finished running startup scripts.
[[0;32m  OK  [0m] Started [0;1;39mGoogle Compute Engine Startup Scripts[0m.
Dec 22 00:43:13 blendnet-s22edw-manager systemd[2353]: blendnet-manager.service: Failed to execute command: Permission denied
Dec 22 00:43:13 blendnet-s22edw-manager systemd[2353]: blendnet-manager.service: Failed at step EXEC spawning /srv/blender/blender: Permission denied
```
```
Jan 4 04:40:04 blendnet-v1azbl-manager systemd[2114]: blendnet-manager.service: Failed to execute command: No such file or directory
Jan 4 04:40:04 blendnet-v1azbl-manager systemd[2114]: blendnet-manager.service: Failed at step EXEC spawning /srv/blender/blender: No such file or directory
```

Not sure what's happening here - but you can check what's inside the VM (if you have ssh access via ssh key).

I updated the master and looks like it should work for you better (at least manager is starting :) So if you will find nothing in v0.3 - I would recommend to use master in your case. For example it could be some filtering proxy on your side which is altering the blender archives and making them useless (like removing executable flags from binaries), but it's hard to say for sure - really depends on the environment of your GCP project...

**Comment by awils27** [comment] 2022-01-04 05:25
I did use a brand new project and haven't altered anything so i'm hopping its set correctly.

Heres the Blender Console
[BlenderConsol.txt](https://github.com/state-of-the-art/BlendNet/files/7805524/BlenderConsol.txt)

**Comment by rabits** [comment] 2022-01-04 05:49
Hmmm, according to the Addon log you provided - now the manager is connected:
```
DEBUG: Periodic update manager info False
DEBUG: Trying to get CA certificate from the bucket
WARNING: Could not acquire lock C:\Users\aid28\AppData\Local\Temp\google-api-python-client-discovery-doc.cache.lock in 0 seconds
INFO: Downloading data from "gs://rendering-335414-blendnet-v1azbl/ca.crt"...
DEBUG: Periodic update manager info True
```
The last line shows it's connected. So now it's working for you?

**Comment by awils27** [comment] 2022-01-04 05:57
Looks like it is, the plugin dialogue in the render panel took a very long time to say it's ready but seems to be working now, i'll do a test render then close this issue.

**Comment by awils27** [comment] 2022-01-04 06:56
The version here works fine but can't render in 3.0, i assume because it isn't updated for 3.0 and the master after your changes doesn't seem to want to connect. It keeps repeating this error:

>INFO: Downloading data from "gs://render_bucket/ca.crt"...
WARN: Downloading failed: <HttpError 404 when requesting https://storage.googleapis.com/storage/v1/b/render_bucket/o/ca.crt?alt=media returned "Not Found". Details: "No such object: render_bucket/ca.crt">
DEBUG: Periodic update manager info False`

Should I just continue with Blender 2.93 for now?

**Comment by awils27** [comment] 2022-01-04 07:12
As a work around using the bucket created by the older version of blendnet seems to allow the version cloned from master to work without issue in Blender 3.0

**Comment by rabits** [comment] 2022-01-04 07:54
Yeah, I think the passwords in blender user settings is different for v3 and v2 or the session ID is different between them - that's why it can't connect well to the previously created manager. Although it's not recommended to mix addon, manager and agents with different versions of Blender - could cause some weird issues.

So if it's working for you now - I will issue new version of v0.3.10 blendnet, but you're free to use master (because actually it's better then the old v0.3 version - I support it just to make sure the users will not be abandoned until v0.4 will be issued).

**Comment by awils27** [comment] 2022-01-04 08:09
Using the existing bucket in GC seems to be the only way to get it to work and a fresh version of master doesn't seem to create the necessary files. Also regardless my instances box is still grayed out.

**Comment by rabits** [comment] 2022-01-04 19:02
Yeah, if you using a different bucket - you will not be able to connect to manager - it stores the ca.crt (certificate of authority) into the bucket with the same session id. Bucket and manager are coupled via session id.

You can't manipulate the agents if the Manager is running - you need to stop it and after that the agents setting will be available. Hopefully later during rewriting of the engine I will be able to make it more dynamic to change the settings on the fly.

**Comment by rabits** [comment] 2022-01-04 22:24
So I hope the issue is resolved and I'm closing it - in case it's not feel free to reopen.

**Closed by rabits** 2022-01-04 22:24 UTC
Labels: bug
